-- INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ('Mr. Chocolate', 12, 'male', 'red', 'angry', true);
-- INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ('Rowdy', 34, 'male', 'black', 'lazy', true);
-- INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ('Tabitha', 16, 'female', 'grey', 'sleepy', true);
-- INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ('Sergeant Brown', 5, 'male', 'yellow', 'spooked', true);
-- INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ('Melissa', 6, 'female', 'silver', 'confused', true);
-- INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ('Grinch', 7, 'male', 'purple', 'happy', true);
-- INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ('Wendy', 2, 'female', 'blonde', 'sad', true);
-- INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES (NULL, 3, 'male', 'blue', 'nothingness', false);